language: python
cache: pip
sudo: required
env:
  - TRAVIS=Y
python:
  - "3.5"
  - "3.6"
services:
  - rabbitmq
before_script:
  - sudo tests/setup_rabbitmq.sh
install:
  - "pip install -v -r requirements.txt"
  - "pip install -v -r requirements_dev.txt"
script: make test
